const {chromium}=require('playwright');const assert=require('assert/strict');
(async()=>{
const b=await chromium.launch({headless:true,executablePath:'/usr/bin/chromium',args:['--no-sandbox']});const p=await b.newPage({viewport:{width:1280,height:900}});const errors=[];p.on('pageerror',e=>errors.push(e.message));
await p.route('**/config.js',r=>r.fulfill({contentType:'application/javascript',body:'window.PORYADOK_CONFIG={supabaseUrl: \"\",supabasePublishableKey: \"\"}'}));await p.goto((process.env.PORYADOK_TEST_URL||'http://127.0.0.1:8001/'));await p.locator('#bulk-button').click();await p.locator('#bulk-text').fill('1. Позвонить поставщику\n- Подготовить презентацию\n3. Позвонить поставщику');assert.match(await p.locator('#bulk-preview').innerText(),/Будет добавлено: 2/);await p.locator('#bulk-submit').click();assert.equal(await p.locator('.task-card').count(),2);await p.locator('.task-card h3').first().click();await p.locator('#note-kind').selectOption('report');await p.locator('#note-text').fill('Согласован счёт <script>alert(1)</script>');await p.locator('#note-form button').click();assert.match(await p.locator('#history').innerText(),/Отчёт о работе/);await p.locator('#note-kind').selectOption('change');await p.locator('#note-text').fill('Добавить доставку');await p.locator('#note-form button').click();await p.locator('#close-dialog').click();await p.reload();await p.locator('.task-card h3').first().click();assert.match(await p.locator('#history').innerText(),/Добавить доставку/);await p.locator('#close-dialog').click();await p.locator('#account-button').click();assert.equal(await p.locator('#login-form').isVisible(),false);assert.match(await p.locator('#account-info').innerText(),/ещё не подключены/);await p.locator('#close-account').click();
const local=await p.evaluate(()=>localStorage.getItem('poryadok.tasks.v1'));
const rows=new Map();let failWrites=false,delayReads=false;
await p.route('**/config.js',r=>r.fulfill({contentType:'application/javascript',body:"window.PORYADOK_CONFIG={supabaseUrl:'https://test-project.supabase.co',supabasePublishableKey:'sb_publishable_test'}"}));
await p.route('https://test-project.supabase.co/**',async r=>{const req=r.request(),url=new URL(req.url()),method=req.method(),auth=req.headers().authorization||'',id=auth==='Bearer token_a'?'a':auth==='Bearer token_b'?'b':null;const body=req.postDataJSON();let status=200,result;
if(url.pathname==='/auth/v1/token'){const user=body.email==='a@example.com'?'a':'b';result={access_token:'token_'+user,refresh_token:'refresh_'+user,expires_at:Math.floor(Date.now()/1000)+3600};}
else if(url.pathname==='/auth/v1/user')result=id?{id,email:id+'@example.com'}:null;
else if(url.pathname==='/auth/v1/logout'){status=204;result=null;}
else if(url.pathname==='/rest/v1/dashboards'){
if(!id){status=401;result={message:'unauthorized'};}
else if(method==='GET'){if(delayReads)await new Promise(resolve=>setTimeout(resolve,600));result=rows.has(id)?[rows.get(id)]:[];}
else if(failWrites){status=503;result={message:'Тест: сеть недоступна'};}
else if(method==='POST'){if(body.user_id!==id){status=403;result={message:'not owner'};}else if(rows.has(id)){status=409;result={message:'duplicate'};}else{rows.set(id,{payload:body.payload,revision:1});result=[rows.get(id)];}}
else if(method==='PATCH'){const revision=Number(url.searchParams.get('revision').replace('eq.',''));if(!rows.has(id)||rows.get(id).revision!==revision)result=[];else{rows.set(id,{payload:body.payload,revision:revision+1});result=[rows.get(id)];}}
}else{status=404;result={message:'unknown'};}await r.fulfill({status,contentType:'application/json',body:status===204?'':JSON.stringify(result)});});
async function login(email){await p.locator('#account-button').click();await p.locator('#login-form [name=email]').fill(email);await p.locator('#login-form [name=password]').fill('a-test-password');await p.locator('#login-form button[type=submit]').click();await p.waitForFunction(()=>document.querySelector('#account-status').textContent.startsWith('Вход выполнен'));}
await p.reload();await login('a@example.com');assert.equal(await p.locator('.task-card').count(),0);p.once('dialog',d=>d.accept());await p.locator('#migrate-local').click();await p.waitForFunction(()=>document.querySelector('#account-status').textContent.startsWith('Задачи добавлены'));assert.equal(rows.get('a').payload.tasks.length,2);await p.locator('#close-account').click();assert.equal(await p.evaluate(()=>localStorage.getItem('poryadok.tasks.v1')),local);
await p.reload();await p.waitForFunction(()=>document.querySelector('#account-button').textContent==='Мой аккаунт');await p.waitForSelector('.task-card');assert.equal(await p.locator('.task-card').count(),2);
rows.get('a').revision++;await p.locator('#quick-title').fill('Не затереть чужую правку');await p.locator('#quick-form button').click();await p.waitForFunction(()=>document.querySelector('#toast').textContent.includes('Данные изменились'));assert.equal(rows.get('a').payload.tasks.length,2);assert.equal(await p.locator('#quick-title').inputValue(),'Не затереть чужую правку');await p.locator('#account-button').click();await p.locator('#cloud-refresh').click();await p.waitForFunction(()=>document.querySelector('#account-status').textContent==='Обновлено из облака.');await p.locator('#close-account').click();failWrites=true;await p.locator('#quick-form button').click();await p.waitForFunction(()=>document.querySelector('#toast').textContent.includes('сеть недоступна'));assert.equal(rows.get('a').payload.tasks.length,2);failWrites=false;
await p.locator('#account-button').click();delayReads=true;rows.get('a').payload.tasks.push({...rows.get('a').payload.tasks[0],id:'cloud-only',title:'Только облако'});await p.locator('#cloud-refresh').click();await p.waitForTimeout(150);await p.locator('#logout').click();await p.waitForFunction(()=>document.querySelector('#account-button').textContent==='Войти');await p.waitForTimeout(800);assert.equal(await p.locator('.task-card').count(),2);delayReads=false;await p.locator('#close-account').click();await p.locator('#quick-title').fill('Локальная после выхода');await p.locator('#quick-form button').click();assert.equal(await p.locator('.task-card').count(),3);await login('b@example.com');assert.equal(await p.locator('.task-card').count(),0);await p.locator('#close-account').click();await p.locator('#quick-title').fill('Личная задача Б');await p.locator('#quick-form button').click();await p.waitForSelector('.task-card');assert.equal(rows.get('b').payload.tasks.length,1);assert.equal(rows.get('a').payload.tasks.length,3);
await p.setViewportSize({width:390,height:844});assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.deepEqual(errors,[]);
const invite=await b.newPage();await invite.route('**/config.js',r=>r.fulfill({contentType:'application/javascript',body:"window.PORYADOK_CONFIG={supabaseUrl:'https://test-project.supabase.co',supabasePublishableKey:'sb_publishable_test'}"}));await invite.goto((process.env.PORYADOK_TEST_URL||'http://127.0.0.1:8001/')+'#error=access_denied&error_code=otp_expired');await invite.waitForFunction(()=>document.querySelector('#account-dialog').open);assert.match(await invite.locator('#account-status').innerText(),/истекла/);assert.equal(await invite.evaluate(()=>location.hash),'');assert.equal(await invite.locator('#login-form').isVisible(),true);
const passwordState=await p.evaluate(async()=>{const c=new DashboardCloud(window.PORYADOK_CONFIG);c.remember({access_token:'token_a',refresh_token:'refresh_a',expires_at:Math.floor(Date.now()/1000)+3600,needs_password:true});await c.restore();const restored=c.needsPassword;await c.password('a-new-test-password');return {restored,cleared:!JSON.parse(sessionStorage.getItem(c.sessionKey)).needs_password};});assert.deepEqual(passwordState,{restored:true,cleared:true});await b.close();console.log('PASS: bulk add/dedup, reports/change journal and escaping, reload, unconfigured UI, mocked login and restore, explicit migration, local/cloud separation, conflict rejection, failed saves, switching accounts, mobile. Mock API tests do NOT validate live Supabase/RLS.');
})().catch(e=>{console.error(e);process.exit(1)});
